### ISSUE TITLE
catalina10.15.16下会重启

### ISSUE THREAD

**Issue by think-ak47** [217heidai/Acer_TraveMate_P249_hackintosh#1]
catalina10.15.16下会重启，CLOVER引导启动过程中，无限循环重启，见不到桌面，但换个CONFIG文件就不会，不知这个CONFIG是哪里设置有问题？

**Comment by 217heidai** [comment]
更新了config文件，再试试

**Comment by think-ak47** [comment]
你好，谢谢你的更新，太厉害了. 你的睡眠唤醒后，会不会卡住只有一个鼠标显示，屏是黑的。其它功能简直是完美了。谢谢了。



在 2020-08-25 09:17:08，"217heidai" <notifications@github.com> 写道：

更新了config文件，再试试
